# 1. Imports

In [36]:
import pandas as pd                         # Manejar DataFrames
from pathlib import Path                    # Manejar rutas

# 2. Paths

In [37]:
PROJECT_ROOT = Path.cwd().parent
PROJECT_ROOT

WindowsPath('c:/Users/Carlos/Documents/Ingenieria_informatica/Proyectos_datascience/2_titanic')

# 3. Import data

In [38]:
df = pd.read_csv(PROJECT_ROOT / 'data' / 'clean' / 'clean_data.csv')

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 76.7 KB

# 4. Feature engineering

## 4.1 PassengerId

El id usualmente no da mucha información, primero veamos cuantas categorías tenemos y luego eliminaremos de ser necesario

In [40]:
df['PassengerId'].nunique()

891

Todos son diferentes, eliminar

In [41]:
df.drop(columns=['PassengerId'], inplace=True)

## 4.2 Name

Al igual que con PassengerId el nombre del pasajero puede no tener que ver con su sobrevivencia

In [42]:
df['Name'].nunique()

891

In [43]:
df.drop(columns=['Name'], inplace=True)

## 4.3 Sex

Como es un str lo vamos a pasar a binario

In [44]:
df['Sex'] = df['Sex'].map({'female': 0, 'male': 1})

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Ticket    891 non-null    str
 7   Fare      891 non-null    float64
 8   Embarked  891 non-null    str
dtypes: float64(2), int64(5), str(2)
memory usage: 62.8 KB

In [46]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,1,22.0,1,0,A/5 21171,7.2500,S
1,1,1,0,38.0,1,0,PC 17599,71.2833,C
2,1,3,0,26.0,0,0,STON/O2. 3101282,7.9250,S
3,1,1,0,35.0,1,0,113803,53.1000,S
4,0,3,1,35.0,0,0,373450,8.0500,S

## 4.4 Ticket

El código de ticket tampoco nos va a revelar mucha información, consideremos eliminarlo

In [47]:
df['Ticket'].nunique()

681

In [48]:
df.drop(columns=['Ticket'], inplace=True)

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    str
dtypes: float64(2), int64(5), str(1)
memory usage: 55.8 KB

## 4.5 Embarked

Para el caso de Embarked, como tenemos pocas categorías, obtenemos su info a través de one-hot-encoding

In [ ]:
# dtype=int para que convierta los bool en 0-1
df = pd.get_dummies(df, dtype=int)

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Sex         891 non-null    int64
 3   Age         891 non-null    float64
 4   SibSp       891 non-null    int64
 5   Parch       891 non-null    int64
 6   Fare        891 non-null    float64
 7   Embarked_C  891 non-null    int64
 8   Embarked_Q  891 non-null    int64
 9   Embarked_S  891 non-null    int64
dtypes: float64(2), int64(8)
memory usage: 69.7 KB

In [52]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,0,3,1,22.0,1,0,7.2500,0,0,1
1,1,1,0,38.0,1,0,71.2833,1,0,0
2,1,3,0,26.0,0,0,7.9250,0,0,1
3,1,1,0,35.0,1,0,53.1000,0,0,1
4,0,3,1,35.0,0,0,8.0500,0,0,1

# 5. Save

In [53]:
df.to_csv(PROJECT_ROOT / 'data' / 'processed' / 'train_data.csv', index=False)