# 1. Imports

In [317]:
import pandas as pd                                     # Manejar DataFrames
from pathlib import Path                                # Manejar rutas
from sklearn.model_selection import train_test_split    # Separar train/test
from sklearn.preprocessing import OneHotEncoder

# 2. Paths

In [318]:
PROJECT_ROOT = Path.cwd().parent
PROJECT_ROOT

WindowsPath('c:/Users/Carlos/Documents/Ingenieria_informatica/Proyectos_datascience/2_titanic')

# 3. Import data

In [319]:
df = pd.read_csv(PROJECT_ROOT / 'data' / 'clean' / 'clean_data.csv')

In [320]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 76.7 KB

# 4. Divide data train/test

Separar datos y respuestas

In [321]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [322]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=42)

# 5. Feature engineering

Primero veamos como quedaron X_train y X_test

In [323]:
X_train.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
331,332,1,"Partner, Mr. Austen",male,45.5,0,0,113043,28.5000,S
733,734,2,"Berriman, Mr. William John",male,23.0,0,0,28425,13.0000,S
382,383,3,"Tikkanen, Mr. Juho",male,32.0,0,0,STON/O 2. 3101293,7.9250,S
704,705,3,"Hansen, Mr. Henrik Juul",male,26.0,1,0,350025,7.8542,S
813,814,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.0,4,2,347082,31.2750,S

In [324]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 712 entries, 331 to 102
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Pclass       712 non-null    int64
 2   Name         712 non-null    str
 3   Sex          712 non-null    str
 4   Age          572 non-null    float64
 5   SibSp        712 non-null    int64
 6   Parch        712 non-null    int64
 7   Ticket       712 non-null    str
 8   Fare         712 non-null    float64
 9   Embarked     710 non-null    str
dtypes: float64(2), int64(4), str(4)
memory usage: 61.2 KB

In [325]:
X_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
709,710,3,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,15.2458,C
439,440,2,"Kvillner, Mr. Johan Henrik Johannesson",male,31.0,0,0,C.A. 18723,10.5000,S
840,841,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,S
720,721,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.0,0,1,248727,33.0000,S
39,40,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,C

In [326]:
X_test.info()

<class 'pandas.DataFrame'>
Index: 179 entries, 709 to 10
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  179 non-null    int64
 1   Pclass       179 non-null    int64
 2   Name         179 non-null    str
 3   Sex          179 non-null    str
 4   Age          142 non-null    float64
 5   SibSp        179 non-null    int64
 6   Parch        179 non-null    int64
 7   Ticket       179 non-null    str
 8   Fare         179 non-null    float64
 9   Embarked     179 non-null    str
dtypes: float64(2), int64(4), str(4)
memory usage: 15.4 KB

## 5.1 Drop unnecessary features

PassengerId, Name y Ticket dificilmente nos pueda dar alguna señal importante, asi que las eliminaremos

In [327]:
total_categories_passengerid = X_train['PassengerId'].nunique()
total_categories_name = X_train['Name'].nunique()
total_categories_ticket = X_train['Ticket'].nunique()
total_rows_xtrain = len(X_train)

In [328]:
print(f"""
Categorias diferentes por filas totales
PassengerId: {total_categories_passengerid}/{total_rows_xtrain}
Name: {total_categories_name}/{total_rows_xtrain}
Ticket: {total_categories_ticket}/{total_rows_xtrain}
""")

Categorias diferentes por filas totales
PassengerId: 712/712
Name: 712/712
Ticket: 558/712

Eliminar (tanto de X_train como de X_test)

In [329]:
X_train.drop(columns=['PassengerId', 'Name', 'Ticket'], inplace=True)
X_test.drop(columns=['PassengerId', 'Name', 'Ticket'], inplace=True)

In [330]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 712 entries, 331 to 102
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    712 non-null    int64
 1   Sex       712 non-null    str
 2   Age       572 non-null    float64
 3   SibSp     712 non-null    int64
 4   Parch     712 non-null    int64
 5   Fare      712 non-null    float64
 6   Embarked  710 non-null    str
dtypes: float64(2), int64(3), str(2)
memory usage: 44.5 KB

In [331]:
X_test.info()

<class 'pandas.DataFrame'>
Index: 179 entries, 709 to 10
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    179 non-null    int64
 1   Sex       179 non-null    str
 2   Age       142 non-null    float64
 3   SibSp     179 non-null    int64
 4   Parch     179 non-null    int64
 5   Fare      179 non-null    float64
 6   Embarked  179 non-null    str
dtypes: float64(2), int64(3), str(2)
memory usage: 11.2 KB

## 5.2 Sex

Mapearemos para convertir a binario

In [332]:
X_train['Sex'] = X_train['Sex'].map({'female': 0, 'male': 1})
X_test['Sex'] = X_test['Sex'].map({'female': 0, 'male': 1})

In [333]:
X_train.head()

     Pclass  Sex   Age  SibSp  Parch     Fare Embarked
331       1    1  45.5      0      0  28.5000        S
733       2    1  23.0      0      0  13.0000        S
382       3    1  32.0      0      0   7.9250        S
704       3    1  26.0      1      0   7.8542        S
813       3    0   6.0      4      2  31.2750        S

In [334]:
X_test.head()

     Pclass  Sex   Age  SibSp  Parch     Fare Embarked
709       3    1   NaN      1      1  15.2458        C
439       2    1  31.0      0      0  10.5000        S
840       3    1  20.0      0      0   7.9250        S
720       2    0   6.0      0      1  33.0000        S
39        3    0  14.0      1      0  11.2417        C

## 5.3 Age

Imputaremos con la mediana

In [335]:
train_median_age = X_train['Age'].median()
train_median_age

np.float64(28.0)

Imputar tanto X_train como X_test

In [336]:
X_train['Age'] = X_train['Age'].fillna(train_median_age)
X_test['Age'] = X_test['Age'].fillna(train_median_age)

In [337]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 712 entries, 331 to 102
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    712 non-null    int64
 1   Sex       712 non-null    int64
 2   Age       712 non-null    float64
 3   SibSp     712 non-null    int64
 4   Parch     712 non-null    int64
 5   Fare      712 non-null    float64
 6   Embarked  710 non-null    str
dtypes: float64(2), int64(4), str(1)
memory usage: 44.5 KB

In [338]:
X_test.info()

<class 'pandas.DataFrame'>
Index: 179 entries, 709 to 10
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    179 non-null    int64
 1   Sex       179 non-null    int64
 2   Age       179 non-null    float64
 3   SibSp     179 non-null    int64
 4   Parch     179 non-null    int64
 5   Fare      179 non-null    float64
 6   Embarked  179 non-null    str
dtypes: float64(2), int64(4), str(1)
memory usage: 11.2 KB

## 5.4 Embarked

### 5.4.1 Fillna

Rellenaremos con moda

In [339]:
train_mode_embarked = X_train['Embarked'].mode().iloc[0]
train_mode_embarked

'S'

In [340]:
X_train['Embarked'] = X_train['Embarked'].fillna(train_mode_embarked)
X_test['Embarked'] = X_test['Embarked'].fillna(train_mode_embarked)

In [341]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 712 entries, 331 to 102
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    712 non-null    int64
 1   Sex       712 non-null    int64
 2   Age       712 non-null    float64
 3   SibSp     712 non-null    int64
 4   Parch     712 non-null    int64
 5   Fare      712 non-null    float64
 6   Embarked  712 non-null    str
dtypes: float64(2), int64(4), str(1)
memory usage: 44.5 KB

In [342]:
X_test.info()

<class 'pandas.DataFrame'>
Index: 179 entries, 709 to 10
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    179 non-null    int64
 1   Sex       179 non-null    int64
 2   Age       179 non-null    float64
 3   SibSp     179 non-null    int64
 4   Parch     179 non-null    int64
 5   Fare      179 non-null    float64
 6   Embarked  179 non-null    str
dtypes: float64(2), int64(4), str(1)
memory usage: 11.2 KB

### 5.4.2 One Hot

Aplicar one-hot encoding para Embarked

El OneHotEncoder va a aprender los 3 tipos de Embarked y transformará la columna en una sparse matrix, que convertida a un array representa con un 1 en donde el registro pertenecía (si cuando transforme el test, aparece una categoría nunca vista, simplemente deja todo en 0)

In [343]:
one_hot_encoder = OneHotEncoder(handle_unknown='ignore')

In [344]:
X_train_encoded_embarked_matrix = one_hot_encoder.fit_transform(X_train[['Embarked']])
X_test_encoded_embarked_matrix = one_hot_encoder.transform(X_test[['Embarked']])

In [345]:
print(X_train_encoded_embarked_matrix.toarray())
print(one_hot_encoder.get_feature_names_out())

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
['Embarked_C' 'Embarked_Q' 'Embarked_S']

Convertir los resultados a un DataFrame para poder luego añadirlos a los datos de entrenamiento y pruebas

In [346]:
X_train_encoded_embarked = pd.DataFrame(
    data=X_train_encoded_embarked_matrix.toarray(),              # Información del DataFrame
    columns=one_hot_encoder.get_feature_names_out(),             # Columnas
    index=X_train.index                                          # Mismo índice que de donde se sacó el One Hot
)

X_test_encoded_embarked = pd.DataFrame(
    data=X_test_encoded_embarked_matrix.toarray(),               # Información del DataFrame
    columns=one_hot_encoder.get_feature_names_out(),             # Columnas
    index=X_test.index                                          # Mismo índice que de donde se sacó el One Hot
)

Añadirlo a los DataFrames originales

In [347]:
X_train = pd.concat(
    [
        X_train.drop(columns=['Embarked']),             # Eliminar columna, ya no va a servir
        X_train_encoded_embarked                        # Embarked codificados
    ],
    axis=1                                              # Unir en eje de las columnas
)

X_test = pd.concat(
    [
        X_test.drop(columns=['Embarked']),
        X_test_encoded_embarked
    ],
    axis=1
)

In [348]:
X_train.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
331,1,1,45.5,0,0,28.5000,0.0,0.0,1.0
733,2,1,23.0,0,0,13.0000,0.0,0.0,1.0
382,3,1,32.0,0,0,7.9250,0.0,0.0,1.0
704,3,1,26.0,1,0,7.8542,0.0,0.0,1.0
813,3,0,6.0,4,2,31.2750,0.0,0.0,1.0

In [349]:
X_test.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
709,3,1,28.0,1,1,15.2458,1.0,0.0,0.0
439,2,1,31.0,0,0,10.5000,0.0,0.0,1.0
840,3,1,20.0,0,0,7.9250,0.0,0.0,1.0
720,2,0,6.0,0,1,33.0000,0.0,0.0,1.0
39,3,0,14.0,1,0,11.2417,1.0,0.0,0.0

In [350]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 712 entries, 331 to 102
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Pclass      712 non-null    int64
 1   Sex         712 non-null    int64
 2   Age         712 non-null    float64
 3   SibSp       712 non-null    int64
 4   Parch       712 non-null    int64
 5   Fare        712 non-null    float64
 6   Embarked_C  712 non-null    float64
 7   Embarked_Q  712 non-null    float64
 8   Embarked_S  712 non-null    float64
dtypes: float64(5), int64(4)
memory usage: 55.6 KB

In [351]:
X_test.info()

<class 'pandas.DataFrame'>
Index: 179 entries, 709 to 10
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Pclass      179 non-null    int64
 1   Sex         179 non-null    int64
 2   Age         179 non-null    float64
 3   SibSp       179 non-null    int64
 4   Parch       179 non-null    int64
 5   Fare        179 non-null    float64
 6   Embarked_C  179 non-null    float64
 7   Embarked_Q  179 non-null    float64
 8   Embarked_S  179 non-null    float64
dtypes: float64(5), int64(4)
memory usage: 14.0 KB

# 6. Save

Guardaremos cada DataFrame para que esté listo para ser utilizado en modeling

In [352]:
X_train.to_csv(PROJECT_ROOT / 'data' / 'processed' / 'x_train.csv', index=False)
X_test.to_csv(PROJECT_ROOT / 'data' / 'processed' / 'x_test.csv', index=False)
y_train.to_csv(PROJECT_ROOT / 'data' / 'processed' / 'y_train.csv', index=False)
y_test.to_csv(PROJECT_ROOT / 'data' / 'processed' / 'y_test.csv', index=False)